baseURL = "https://blog.mikkel.cc/"
languageCode = "en-us"
title = "Mikkel Jeppesens ramblings"
googleAnalytics = "G-09MS4W73S3"
theme = "m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
    author = "Mikkel Jeppesen"
    description = """
    B.Sc. in EE, M.Sc. in Ai and computer vision. 
    Having fun with IoT and keyboards in my spare time.
    """
    avatar = "avatar180x180.png"
    menu_item_separator = " - "
    
    [[params.social]]
    name = "github"
    url = "https://github.com/Duckle29"


